import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Data from "../components/Data";
import Cloud from "../components/Cloud";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<header className="sticky top-0 z-50 bg-black">
					<Navbar />
				</header>

				<div id="hero" className="">
					<div
						className="bg-scroll bg-[url('/background.jpg')] min-h-screen "
						style={{
							backgroundSize: "cover",
							backgroundAttachment: "fixed",
						}}
					>
						<div className="flex flex-col items-center justify-between pt-[25rem] pb-[3rem]">
							<div className="text-start pl-0 w-9/12">
								<div className="text-[130px] font-bold flex space-x-12 ">
									<div className="drop-shadow-xl">Smart</div>
									<div className="group">
										<div className="drop-shadow-xl cursor-pointer underline-offset-4 underline decoration-sky-400">
											Agronomy
										</div>
										<div className="text-end text-[30px]">
											The science of soil management and crop production
										</div>
									</div>
								</div>
							</div>

							<div className="text-xl text-center py-2 px-4 bg-black text-white mt-96 items-center w-80">
								We equip our growers with data-driven soil and crop insights
							</div>
						</div>
					</div>
				</div>

				<div className="min-h-screen grid grid-cols-1 divide-y-2 divide-gray-200 py-32 text-black px-32">
					<Data />
					<Cloud />
					<div className="h-80">Our Data</div>
					<div className="h-80">Our Data</div>
					<div className="h-80">Our Data</div>
				</div>
			</main>
		</div>
	);
}
